### ISSUE TITLE
User can view detailed description of achievement

### ISSUE THREAD

**Issue by michaellennox** [michaellennox/netstix#20]
As a user
So I can know WTF I need to do
I want to be able to view further detail about an achievement on it's page

**Comment by michaellennox** [comment]
- [x] #25 extend userflow diagram
- [x] #19 create API route for GET /achievements/:id
- [x] #22 extend original protractor test for new route
- [x] #23 create HTML view for /achievements/:id
- [x] #24 create angular controller for achievements/:id
