### ISSUE TITLE
User Authentication With Passport

### ISSUE THREAD

**Issue by michaellennox** [michaellennox/netstix#33]
Time to use passport.

Don't worry about restricted routes on the front end yet, just get the use authentication system up and running.

We will follow the below with some minor modifications

http://mherman.org/blog/2015/07/02/handling-user-authentication-with-the-mean-stack/#.VrDcM1OLSqR

As a user
So I can keep track of my data
I want to be able to have an account on the awesome service built by team netstix

API endpoints:
POST /users - create user
POST /sessions - create session
DELETE /sessions - close session

Angular Routes
/register - sign up form, POSTs to /users
/login - sign in form, POSTs to /sessions
/logout - sign out form, DELETEs to /sessions

All errors in these routes will return a json response containing {err : 'whattheerrorwas'} and a relevant status code

The success codes and JSON response are included in the client side tickets

**Comment by michaellennox** [comment]
- [x] #46 map user flow
- [x] #45 create protractor feature test to follow user flow
- [x] #40 passport config and user model
- [x] #41 user auth API endpoints
- [x] #54 create fizby tests for user auth
- [x] #47 build UserAuth factory
- [x] #42 client /login jazz
- [x] #43 client /register jazz
- [x] #44 client /logout button jazz
